# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: recursive
  lfs: false
  persistCredentials: true

- task: DownloadSecureFile@1
  displayName: 'Download DoxyGen'
  name: doxygen
  inputs:  
    secureFile: 'doxygen.zip'

- task: Bash@3
  displayName: 'Unzip DoxyGen executable'
  inputs:
    targetType: 'inline'
    script: 'unzip "$(doxygen.secureFilePath)" -d .'

- task: Bash@3
  displayName: 'Mark DoxyGen as executable'
  inputs:
    targetType: 'inline'
    script: 'chmod +x doxygen'

- task: Bash@3
  displayName: 'Install  GraphViz'
  inputs:
    targetType: 'inline'
    script: 'sudo apt-get install graphviz'

- task: Bash@3
  displayName: 'Generate HTML documentation'
  inputs:
    targetType: 'inline'
    script: |
      cd docs
      '$(build.sourcesdirectory)'/doxygen
      cd $(build.sourcesdirectory)

- task: Bash@3
  displayName: 'Generate HTML documentation for APIs'
  inputs:
    targetType: 'inline'
    script: |
      for api in `find ./apis -mindepth 1 -maxdepth 1 -type d`; do
        cd ${api}/docs
        '$(build.sourcesdirectory)'/doxygen
        cd $(build.sourcesdirectory)
      done


- task: Bash@3
  displayName: 'Commit and push HTML docs'
  inputs:
    targetType: 'inline'
    script: |
      echo "Commiting ${api}"
      mv $(apiversion) $(apiversion)new
      [ -f docs/tagfile ] && git checkout -- docs/tagfile
      git checkout gh-pages
      [ -d "$(apiversion)" ] && rm -r $(apiversion)
      mv $(apiversion)new $(apiversion)
      git add $(apiversion)
      git status
      git commit -m "DOC: Regenerated HTML documentation pages."
      git status
      git push origin gh-pages

- task: Bash@3
  displayName: 'Commit and push HTML docs for APIs'
  inputs:
    targetType: 'inline'
    script: |
      for api in `find ./apis -mindepth 1 -maxdepth 1 -type d`; do
        cd ${api}
        echo "Commiting ${api}"
        mv $(apiversion) $(apiversion)new
        [ -f docs/tagfile ] && git checkout -- docs/tagfile
        git checkout gh-pages
        [ -d "$(apiversion)" ] && rm -r $(apiversion)
        mv $(apiversion)new $(apiversion)
        git add $(apiversion)
        git config --global user.name "51Degrees"
        git config --global user.email "CI@51degrees.com"
        git status
        git commit -m "DOC: Regenerated HTML documentation pages."
        git push origin gh-pages
        cd $(build.sourcesdirectory)
      done

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  condition: true
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: 'docs/$(apiversion)/**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish HTML docs'
  condition: true
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'docs'
    publishLocation: 'Container'