var classfiftyone__devicedetection__onpremise_1_1_device_detection_hash_engine_module_1_1_evidence_device_detection_swig =
[
    [ "__init__", "classfiftyone__devicedetection__onpremise_1_1_device_detection_hash_engine_module_1_1_evidence_device_detection_swig.html#ab4e0c45f0429714e2c33fcac8a7e44f8", null ],
    [ "thisown", "classfiftyone__devicedetection__onpremise_1_1_device_detection_hash_engine_module_1_1_evidence_device_detection_swig.html#aa9bcb4b1a724ea6e20c50ecfa59531a6", null ]
];