// Generated - one story per source pattern (see _gen-stories.mjs).
import { renderPattern } from './render-twig.js';

export default { title: "Components" };

export const Brand = () => renderPattern("components-brand");
Brand.storyName = "brand";
export const Progress = () => renderPattern("components-progress");
Progress.storyName = "progress";
export const Sidenav = () => renderPattern("components-sidenav");
Sidenav.storyName = "sidenav";
export const Breadcrumb = () => renderPattern("components-breadcrumb");
Breadcrumb.storyName = "breadcrumb";
export const SectionNav = () => renderPattern("components-section-nav");
SectionNav.storyName = "section-nav";
export const SubNav = () => renderPattern("components-sub-nav");
SubNav.storyName = "sub-nav";
export const Category = () => renderPattern("components-category");
Category.storyName = "category";
export const CategoryHeader = () => renderPattern("components-category-header");
CategoryHeader.storyName = "category-header";
export const Option = () => renderPattern("components-option");
Option.storyName = "option";
export const Select = () => renderPattern("components-select");
Select.storyName = "select";
export const Search = () => renderPattern("components-search");
Search.storyName = "search";
export const Filter = () => renderPattern("components-filter");
Filter.storyName = "filter";
export const CodeExample = () => renderPattern("components-code-example");
CodeExample.storyName = "code-example";
export const CodePrettify = () => renderPattern("components-code-prettify");
CodePrettify.storyName = "code-prettify";
export const Code = () => renderPattern("components-code");
Code.storyName = "code";
export const Prettify = () => renderPattern("components-prettify");
Prettify.storyName = "prettify";
export const Outputs = () => renderPattern("components-outputs");
Outputs.storyName = "outputs";
export const TopLink = () => renderPattern("components-top-link");
TopLink.storyName = "top-link";
export const Card = () => renderPattern("components-card");
Card.storyName = "card";
export const CardDomains = () => renderPattern("components-card-domains");
CardDomains.storyName = "card-domains";
export const CardRegister = () => renderPattern("components-card-register");
CardRegister.storyName = "card-register";
export const CardShare = () => renderPattern("components-card-share");
CardShare.storyName = "card-share";
export const TableDirectory = () => renderPattern("components-table-directory");
TableDirectory.storyName = "table-directory";
export const TableMembers = () => renderPattern("components-table-members");
TableMembers.storyName = "table-members";
export const TableArticle = () => renderPattern("components-table-article");
TableArticle.storyName = "table-article";
export const TableInvert = () => renderPattern("components-table-invert");
TableInvert.storyName = "table-invert";
export const TablePackages = () => renderPattern("components-table-packages");
TablePackages.storyName = "table-packages";
export const ListDefinition = () => renderPattern("components-list-definition");
ListDefinition.storyName = "list-definition";
export const Member = () => renderPattern("components-member");
Member.storyName = "member";
