// Generated - one story per source pattern (see _gen-stories.mjs).
import { renderPattern } from './render-twig.js';

export default { title: "Groups" };

export const Panel = () => renderPattern("groups-panel-");
Panel.storyName = "panel-";
export const PanelCategories = () => renderPattern("groups-panel-categories");
PanelCategories.storyName = "panel-categories";
export const PanelDetails = () => renderPattern("groups-panel-details");
PanelDetails.storyName = "panel-details";
export const PanelImplement = () => renderPattern("groups-panel-implement");
PanelImplement.storyName = "panel-implement";
export const PanelImplementations = () => renderPattern("groups-panel-implementations");
PanelImplementations.storyName = "panel-implementations";
export const PanelOption = () => renderPattern("groups-panel-option");
PanelOption.storyName = "panel-option";
export const PanelOptions = () => renderPattern("groups-panel-options");
PanelOptions.storyName = "panel-options";
export const PanelShare = () => renderPattern("groups-panel-share");
PanelShare.storyName = "panel-share";
export const PanelSubcategories = () => renderPattern("groups-panel-subcategories");
PanelSubcategories.storyName = "panel-subcategories";
export const Info = () => renderPattern("groups-info");
Info.storyName = "info";
export const InfoDetails = () => renderPattern("groups-info-details");
InfoDetails.storyName = "info-details";
export const InfoImplement = () => renderPattern("groups-info-implement");
InfoImplement.storyName = "info-implement";
export const InfoOption = () => renderPattern("groups-info-option");
InfoOption.storyName = "info-option";
export const InfoShare = () => renderPattern("groups-info-share");
InfoShare.storyName = "info-share";
export const Header = () => renderPattern("groups-header");
Header.storyName = "header";
export const Basket = () => renderPattern("groups-basket");
Basket.storyName = "basket";
export const HeaderDocs = () => renderPattern("groups-header-docs");
HeaderDocs.storyName = "header-docs";
export const Options = () => renderPattern("groups-options");
Options.storyName = "options";
export const Search = () => renderPattern("groups-search");
Search.storyName = "search";
export const DocsBasic = () => renderPattern("groups-docs-basic");
DocsBasic.storyName = "docs-basic";
export const DocsDirectory = () => renderPattern("groups-docs-directory");
DocsDirectory.storyName = "docs-directory";
export const DocsMembers = () => renderPattern("groups-docs-members");
DocsMembers.storyName = "docs-members";
export const DocsMemberArticle = () => renderPattern("groups-docs-member-article");
DocsMemberArticle.storyName = "docs-member-article";
export const DocsCode = () => renderPattern("groups-docs-code");
DocsCode.storyName = "docs-code";
export const Main = () => renderPattern("groups-main");
Main.storyName = "main";
export const ExampleBlock = () => renderPattern("groups-example-block");
ExampleBlock.storyName = "example-block";
export const FooterDocs = () => renderPattern("groups-footer-docs");
FooterDocs.storyName = "footer-docs";
export const Footer = () => renderPattern("groups-footer");
Footer.storyName = "footer";
export const FooterConfigure = () => renderPattern("groups-footer-configure");
FooterConfigure.storyName = "footer-configure";
export const FooterDetails = () => renderPattern("groups-footer-details");
FooterDetails.storyName = "footer-details";
export const FooterImplement = () => renderPattern("groups-footer-implement");
FooterImplement.storyName = "footer-implement";
export const FooterShare = () => renderPattern("groups-footer-share");
FooterShare.storyName = "footer-share";
export const ExamplePrettify = () => renderPattern("groups-example-prettify");
ExamplePrettify.storyName = "example-prettify";
