name: Cleanup Preview

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

concurrency:
  group: doc-preview-push
  queue: max

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/doc-preview
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Cleanup preview
        env:
          BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
        run: |
          set -x
          git rm -rf "${BRANCH//[\/]/-}"
          git -c user.name=Automation51D -c user.email=60396166+Automation51D@users.noreply.github.com commit --amend --no-edit --reset-author
          git push --force-with-lease || sleep 5 && git pull --rebase && git push --force-with-lease
